### ISSUE TITLE
Code?

### ISSUE THREAD

**Issue by YuweiHuang** [skasewa/wronging#1]
Hey, friend,  when do you decide to release your code for this paper? You are doing a good job for GEC community!

**Comment by yanshengjia** [comment]
+1

**Comment by skasewa** [comment]
@YuweiHuang @yanshengjia Thank you for your patience! A working version has been uploaded, and README should be up in an hour. Please try to get it to run (tf. 1.12.0, numpy 1.14.0), and let me know if you face any issues.

**Comment by skasewa** [comment]
README is up, closing this issue.
