### ISSUE TITLE
Pre-trained model?

### ISSUE THREAD

**Issue by pabloppp** [skasewa/wronging#2]
Since you train your model on a publicly available dataset, is there any chance you'll publish a pre-trained model to use for inference only and avoid other people having to re-train the model in the same dataset? 
Thanks!!! 
🙇

**Comment by skasewa** [comment]
While the data is "public" insomuch as it doesn't need to be bought, some of it (FCE) is still curated/licensed. To use the data, one would need to get it from the maintainers. Since I cannot guarantee that a trained model does not leak the data in some way, I won't be releasing a trained model.
