### ISSUE TITLE
targets.txt

### ISSUE THREAD

**Issue by LNdoremi** [skasewa/wronging#3]
hello, how to use fce xml files to generate targets.txt ?

**Comment by skasewa** [comment]
The FCE xml files contain sentences and their corrections (as xml annotations). You would need to write a script that constructs a parallel corpus from the xmls, like this one:

https://github.com/nusnlp/mlconvgec2018/blob/master/scripts/convert_m2_to_parallel.py

^^ This one is for m2 format, but it is straight-forward to write one for the FCE xml format.

**Comment by LNdoremi** [comment]
Hi Skasewa! Thank you very much for your reply. It is helpful.
