### ISSUE TITLE
Dataset format for Seq2Seq training

### ISSUE THREAD

**Issue by gcunhase** [skasewa/wronging#4]
Hello, thank you for releasing this code!

I'm trying to run the [`s2s-training.sh`](https://github.com/skasewa/wronging/blob/master/seq2seq/scripts/s2s-training.sh) script and I was wondering if you could release the script used to convert the FCE released dataset to `vocab.txt`, `targets.txt` and `sources.txt`. Also, how was the train-dev-test division done?

Thank you in advance

**Comment by skasewa** [comment]
Hi, Thanks for your writing in, hope you find this repository useful.

The script is part of another codebase, which I am not at liberty to share ; however, it is straightforward to write a script that converts the FCE xmls into sources.txt and targets.txt ; vocab.txt can then easily be generated from sources.txt by just reading the file, splitting/tokenizing, and using np.unique( ) .

The train-dev-test splits where according to the splits given in the Error Detection dataset as provided here: https://ilexir.co.uk/datasets/index.html

**Comment by gcunhase** [comment]
Thank you for your answer,
I'm implementing this now, but I have a question about the `sources.txt`, `targets.txt` and `vocab.txt`data.

1. In `sources.txt` and  `targets.txt`, is each line an essay (with multiple sentences) or is it one sentence per line?

2. In `vocab.txt`, is each line a word?

Thank you in advance

**Comment by skasewa** [comment]
`sources.txt` and `targets.txt` have one sentence per line. The same line-number in each file have incorrect and corrected versions of the same sentence; in this way, they are a parallel corpus.

You are correct, `vocab.txt` has a single work for line. You should generate `vocab.txt` using the utilities given in https://github.com/skasewa/wronging/tree/master/seq2seq/bin/tools

**Comment by gcunhase** [comment]
Thank you for your help, I think I've successfully formatted the `xml` data into `txt` data to use with your model. If it's okay I'd like to share it here so other people can also use it and check for errors.

Link to the repository (XML to TXT): https://github.com/gcunhase/FCECorpusXML

**Comment by skasewa** [comment]
Thank you @gcunhase, this is great. Closing this issue.
